-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 创建资源交换表
CREATE TABLE IF NOT EXISTS public.resources (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  category TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('提供', '需求')),
  contact_info TEXT,
  images TEXT[],
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'completed', 'cancelled')),
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 创建活动通知表
CREATE TABLE IF NOT EXISTS public.events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  location TEXT NOT NULL,
  event_date TIMESTAMP NOT NULL,
  end_date TIMESTAMP,
  category TEXT NOT NULL,
  max_participants INTEGER,
  current_participants INTEGER DEFAULT 0,
  images TEXT[],
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  status TEXT DEFAULT 'upcoming' CHECK (status IN ('upcoming', 'ongoing', 'completed', 'cancelled')),
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 创建活动报名记录表
CREATE TABLE IF NOT EXISTS public.event_registrations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id UUID REFERENCES public.events(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  registered_at TIMESTAMP DEFAULT NOW(),
  status TEXT DEFAULT 'registered' CHECK (status IN ('registered', 'cancelled', 'attended')),
  UNIQUE(event_id, user_id)
);

-- 创建用户资料表
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username TEXT UNIQUE,
  avatar_url TEXT,
  bio TEXT,
  location TEXT DEFAULT '合肥',
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 启用行级安全
ALTER TABLE public.resources ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- 资源表策略
CREATE POLICY "所有人可查看活跃资源" ON public.resources
  FOR SELECT USING (status = 'active');

CREATE POLICY "认证用户可创建资源" ON public.resources
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "资源所有者可更新自己的资源" ON public.resources
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "资源所有者可删除自己的资源" ON public.resources
  FOR DELETE USING (auth.uid() = user_id);

-- 活动表策略
CREATE POLICY "所有人可查看活动" ON public.events
  FOR SELECT USING (true);

CREATE POLICY "认证用户可创建活动" ON public.events
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "活动创建者可更新自己的活动" ON public.events
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "活动创建者可删除自己的活动" ON public.events
  FOR DELETE USING (auth.uid() = user_id);

-- 活动报名策略
CREATE POLICY "所有人可查看报名记录" ON public.event_registrations
  FOR SELECT USING (true);

CREATE POLICY "认证用户可报名活动" ON public.event_registrations
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "用户可取消自己的报名" ON public.event_registrations
  FOR UPDATE USING (auth.uid() = user_id);

-- 用户资料策略
CREATE POLICY "所有人可查看用户资料" ON public.profiles
  FOR SELECT USING (true);

CREATE POLICY "用户可管理自己的资料" ON public.profiles
  FOR ALL USING (auth.uid() = id);

-- 创建新用户时自动创建资料
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, username, avatar_url)
  VALUES (
    NEW.id,
    NEW.raw_user_meta_data ->> 'username',
    NEW.raw_user_meta_data ->> 'avatar_url'
  );
  RETURN NEW;
END;
$$;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();