-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

CREATE OR REPLACE VIEW auth_users_view AS
SELECT id, email
FROM auth.users;

ALTER VIEW auth_users_view OWNER TO postgres;